name : Front CI Pipeline
on:
  push:
    branches: ["main","dev"]
  pull_request:
    branches: ["main","dev"]
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
    build-and-test:
      runs-on: ubuntu-latest

      steps:
        - name: Descargar repositorio
          uses: actions/checkout@v4

        - name: Configurar Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 24
            cache: 'npm'

        - name: Instalar dependencias
          run: npm ci

        - name: Validar Linting
          run: npm run lint

        - name: Compilador Proyecto(build)
          run: npm run build

        - name: Subir artefacto de pages
          uses: actions/upload-pages-artifact@v3
          with:
            path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'

    steps:
      - name: Desplegar a Github pages
        id: deployment
        uses: actions/deploy-pages@v4